### ISSUE TITLE
Zombie Collision

### ISSUE THREAD

**Issue by Salah19984** [Ychop/CG_Projekt#12]
Flocking verhalten einfügen 
(Tutorial: 
https://natureofcode.com/book/
https://fbe-gitlab.hs-weingarten.de/scherzer/creative-coding/-/blob/master/agents/agents.md
)

oder
zombies verschmelzen zu einem großen zombie bei berührung

**Comment by Ychop** [comment]
Spieler sollte nicht überZombies Alfuen können
evlt. Verlangsamen die Zombies den spieler.
